server:
  port: 8181

management:
  endpoint:
    web:
      exposure:
        include: health
    health:
      probes: true
    metrics:
      enabled: true

springdoc:
  swagger-ui:
    enabled: true
    path: /tradetheday/swagger.html
  api-docs:
    path: /tradetheday/docs
spring:
  application:
    name: trade-signal
  r2dbc:
    username: user
    password: password
    url: r2dbc:postgresql://localhost:5432/tradetheday
  flyway:
    url: jdbc:postgresql://localhost:5432/tradetheday
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
binance:
  apiuri: https://api.binance.com
  shortma: 9
  longma: 21
  extracandles: 15
  profit: 1.02
  stop: 0.98
  symbols:
    - MANAUSDT
    - BATUSDT
    - CHZUSDT
    - COMPUSDT
    - SANDUSDT
    - ADAUSDT
    - XLMUSDT
    - AUDIOUSDT
    - ZRXUSDT
    - XRPUSDT
    - AVAXUSDT
    - LINKUSDT
    - LTCUSDT
    - AAVEUSDT
    - SLPUSDT
    - DOTUSDT
    - MKRUSDT
    - AXSUSDT
    - FETUSDT
    - BCHUSDT
    - GRTUSDT
    - SKLUSDT
    - FTMUSDT
    - HBARUSDT
    - MATICUSDT
    - SOLUSDT
    - BTCUSDT
kraken:
  apiuri: https://api.kraken.com
  apikey:
  apisecret:
  shortma: 9
  longma: 21
  extracandles: 15
  profit: 1.04
  stop: 0.98
  symbols:
    - DOTUSD
    - 1INCHUSD
    - AAVEUSD
    - ACAUSD
    - ACHUSD
    - ADAUSD
    - ADAUSDT
    - ADXUSD
    - AEVOUSD
    - AGLDUSD
    - AIRUSD
    - AKTUSD
    - ALCXUSD
    - ALGOUSD
    - ALGOUSDT
    - ALICEUSD
    - ALPHAUSD
    - ALTUSD
    - ANKRUSD
    - ANTUSD
    - APEUSD
    - APEUSDT
    - API3USD
    - APTUSD
    - ARBUSD
    - ARKMUSD
    - ARPAUSD
    - ASTRUSD
    - ATLASUSD
    - ATOMUSD
    - ATOMUSDT
    - AUDIOUSD
    - AUDUSD
    - AVAXUSD
    - AVAXUSDT
    - AXSUSD
    - BADGERUSD
    - BALUSD
    - BANDUSD
    - BATUSD
    - BCHUSD
    - BCHUSDT
    - BEAMUSD
    - BICOUSD
    - BITUSD
    - BLURUSD
    - BLZUSD
    - BNCUSD
    - BNTUSD
    - BOBAUSD
    - BODENUSD
    - BONDUSD
    - BONKUSD
    - BRICKUSD
    - BSXUSD
    - BTTUSD
    - C98USD
    - CELRUSD
    - CFGUSD
    - CHRUSD
    - CHZUSD
    - COMPUSD
    - COTIUSD
    - CQTUSD
    - CRVUSD
    - CSMUSD
    - CTSIUSD
    - CVCUSD
    - CVXUSD
    - DAIUSD
    - DAIUSDT
    - DASHUSD
    - DENTUSD
    - DOTUSD
    - DOTUSDT
    - DYDXUSD
    - DYMUSD
    - EGLDUSD
    - ENAUSD
    - ENJUSD
    - ENSUSD
    - EOSUSD
    - EOSUSDT
    - ETHFIUSD
    - ETHPYUSD
    - ETHUSDC
    - ETHUSDT
    - ETHWUSD
    - EULUSD
    - EURTUSD
    - EURTUSDT
    - EWTUSD
    - FARMUSD
    - FETUSD
    - FIDAUSD
    - FILUSD
    - FISUSD
    - FLOWUSD
    - FLRUSD
    - FORTHUSD
    - FTMUSD
    - FXSUSD
    - GALAUSD
    - GALUSD
    - GARIUSD
    - GHSTUSD
    - GLMRUSD
    - GMTUSD
    - GMXUSD
    - GNOUSD
    - GRTUSD
    - GSTUSD
    - GTCUSD
    - HDXUSD
    - HFTUSD
    - HNTUSD
    - ICPUSD
    - ICXUSD
    - IDEXUSD
    - IMXUSD
    - INJUSD
    - INTRUSD
    - JASMYUSD
    - JTOUSD
    - JUNOUSD
    - JUPUSD
    - KARUSD
    - KAVAUSD
    - KEEPUSD
    - KEYUSD
    - KILTUSD
    - KINTUSD
    - KINUSD
    - KNCUSD
    - KP3RUSD
    - KSMUSD
    - LCXUSD
    - LDOUSD
    - LINKUSD
    - LINKUSDT
    - LMWRUSD
    - LPTUSD
    - LRCUSD
    - LTCUSDT
    - LUNA2USD
    - LUNAUSD
    - MANAUSD
    - MANAUSDT
    - MASKUSD
    - MATICUSD
    - MATICUSDT
    - MCUSD
    - MINAUSD
    - MIRUSD
    - MKRUSD
    - MNGOUSD
    - MOONUSD
    - MOVRUSD
    - MPLUSD
    - MSOLUSD
    - MULTIUSD
    - MVUSD
    - MXCUSD
    - NANOUSD
    - NEARUSD
    - NMRUSD
    - NODLUSD
    - NOSUSD
    - NYMUSD
    - OCEANUSD
    - OGNUSD
    - OMGUSD
    - ONDOUSD
    - OPUSD
    - ORCAUSD
    - OXTUSD
    - OXYUSD
    - PAXGUSD
    - PDAUSD
    - PENDLEUSD
    - PEPEUSD
    - PERPUSD
    - PHAUSD
    - POLISUSD
    - POLSUSD
    - POLUSD
    - PONDUSD
    - POWRUSD
    - PSTAKEUSD
    - PYTHUSD
    - PYUSDEUR
    - PYUSDUSD
    - QNTUSD
    - QTUMUSD
    - RADUSD
    - RAREUSD
    - RARIUSD
    - RAYUSD
    - RBCUSD
    - RENUSD
    - REPV2USD
    - REQUSD
    - RLCUSD
    - RNDRUSD
    - ROOKUSD
    - RPLUSD
    - RUNEUSD
    - SAFEUSD
    - SAMOUSD
    - SANDUSD
    - SBRUSD
    - SCRTUSD
    - SCUSD
    - SDNUSD
    - SEIUSD
    - SGBUSD
    - SHIBUSD
    - SHIBUSDT
    - SNXUSD
    - SOLUSD
    - SOLUSDT
    - SPELLUSD
    - SRMUSD
    - STEPUSD
    - STGUSD
    - STORJUSD
    - STRKUSD
    - STXUSD
    - SUIUSD
    - SUPERUSD
    - SUSHIUSD
    - SYNUSD
    - TBTCUSD
    - TEERUSD
    - TIAUSD
    - TLMUSD
    - TNSRUSD
    - TOKEUSD
    - TREMPUSD
    - TRUUSD
    - TRXUSD
    - TUSD
    - TUSDEUR
    - TUSDUSD
    - TVKUSD
    - UMAUSD
    - UNFIUSD
    - UNIUSD
    - USDCAUD
    - USDCCAD
    - USDCCHF
    - USDCEUR
    - USDCGBP
    - USDCHF
    - USDCUSD
    - USDCUSDT
    - USDTAUD
    - USDTCAD
    - USDTCHF
    - USDTEUR
    - USDTGBP
    - USDTJPY
    - USDTZUSD
    - USTUSD
    - USTUSDC
    - USTUSDT
    - WAVESUSD
    - WAXLUSD
    - WBTCUSD
    - WENUSD
    - WIFUSD
    - WOOUSD
    - WUSD
    - XBTPYUSD
    - XBTUSDC
    - XBTUSDT
    - XCNUSD
    - XDGUSD
    - XDGUSDT
    - XETCZUSD
    - XETHZUSD
    - XLTCZUSD
    - XMLNZUSD
    - XMRUSDT
    - XREPZUSD
    - XRPUSDT
    - XRTUSD
    - XTZUSD
    - XTZUSDT
    - XXBTZUSD
    - XXLMZUSD
    - XXMRZUSD
    - XXRPZUSD
    - XZECZUSD
    - YFIUSD
    - YGGUSD
    - ZETAUSD
    - ZEURZUSD
    - ZEUSUSD
    - ZGBPZUSD
    - ZRXUSD
    - ZUSDZCAD
    - ZUSDZJPY
