INSERT INTO opportunity(opportunityid,
                        binanceengulfing,
                        binanceengulfingtime,
                        binancema,
                        binancematime,
                        binanceprice,
                        binancestop,
                        binanceprofit,
                        krakenengulfing,
                        krakenengulfingtime,
                        krakenma,
                        krakenmatime,
                        krakenprice,
                        krakenstop,
                        krakenprofit,
                        version)
VALUES('BTCUSDT-H1', TRUE, 1718545121, FALSE, 1718545121, 2.0, 1.8, 2.2, TRUE, 1718545121, FALSE, 1718545121, 2.0, 1.8, 2.2, 0);

INSERT INTO opportunity(opportunityid,
                        binanceengulfing,
                        binanceengulfingtime,
                        binancema,
                        binancematime,
                        binanceprice,
                        binancestop,
                        binanceprofit,
                        krakenengulfing,
                        krakenengulfingtime,
                        krakenma,
                        krakenmatime,
                        krakenprice,
                        krakenstop,
                        krakenprofit,
                        version)
VALUES('ADAUSD-H1', TRUE, 1718996982, TRUE, 1718996982,  2.0, 1.8, 2.2, TRUE,  1718996982, TRUE, 1718996982,  2.0, 1.8, 2.2, 0);

INSERT INTO opportunity(opportunityid,
                        binanceengulfing,
                        binanceengulfingtime,
                        binancema,
                        binancematime,
                        binanceprice,
                        binancestop,
                        binanceprofit,
                        krakenengulfing,
                        krakenengulfingtime,
                        krakenma,
                        krakenmatime,
                        krakenprice,
                        krakenstop,
                        krakenprofit,
                        version)
VALUES('SOLUSD-H1', TRUE, 1718996982, FALSE, 1718996982,  2.0, 1.8, 2.2, TRUE,  1718996982, TRUE, 1718996982,  2.0, 1.8, 2.2, 0);

INSERT INTO opportunity(opportunityid,
                        binanceengulfing,
                        binanceengulfingtime,
                        binancema,
                        binancematime,
                        binanceprice,
                        binancestop,
                        binanceprofit,
                        krakenengulfing,
                        krakenengulfingtime,
                        krakenma,
                        krakenmatime,
                        krakenprice,
                        krakenstop,
                        krakenprofit,
                        version)
VALUES('XMRUSD-D1', FALSE, 1718996982, TRUE, 1718996982,  2.0, 1.8, 2.2, TRUE,  1718996982, TRUE, 1718996982,  2.0, 1.8, 2.2, 0);

INSERT INTO opportunity(opportunityid,
                        binanceengulfing,
                        binanceengulfingtime,
                        binancema,
                        binancematime,
                        binanceprice,
                        binancestop,
                        binanceprofit,
                        krakenengulfing,
                        krakenengulfingtime,
                        krakenma,
                        krakenmatime,
                        krakenprice,
                        krakenstop,
                        krakenprofit,
                        version)
VALUES('BTCUSD-D1', FALSE, 1718996982, FALSE, 1718996982,  2.0, 1.8, 2.2, TRUE,  1718996982, TRUE, 1718996982,  2.0, 1.8, 2.2, 0);



INSERT INTO opportunity(opportunityid,
                        binanceengulfing,
                        binanceengulfingtime,
                        binancema,
                        binancematime,
                        binanceprice,
                        binancestop,
                        binanceprofit,
                        krakenengulfing,
                        krakenengulfingtime,
                        krakenma,
                        krakenmatime,
                        krakenprice,
                        krakenstop,
                        krakenprofit,
                        version)
VALUES('SOLUSD-H4', FALSE, 1718996982, FALSE, 1718996982,  2.0, 1.8, 2.2, FALSE,  1718996982, TRUE, 1718996982,  2.0, 1.8, 2.2, 0);
